### ISSUE TITLE
yaml.load deprecated and FileNotFoundError when running ./seed-via-docker.sh as per instructions

### ISSUE THREAD

**Issue by rduerr** [INCATools/ontology-development-kit#202] opened 2019-03-18 22:13 UTC
Here is the error that returned:

$ ./seed-via-docker.sh -C project.yaml
/tools/odk.py:439: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  obj = yaml.load(config_file)
Traceback (most recent call last):
  File "/tools/odk.py", line 673, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tools/odk.py", line 629, in seed
    save_project_yaml(project, tgt_project_file)
  File "/tools/odk.py", line 464, in save_project_yaml
    with open(path, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'target/ecrro/project.yaml'

**Comment by matentzn** [comment] 2019-03-18 22:15
I think the problem is that the target path is hard coded.. Can you make sure that relative to the seed-via-docker.sh file, there is also a target directory? Would this work?

**Comment by rduerr** [comment] 2019-03-18 22:16
I will try that now

**Comment by rduerr** [comment] 2019-03-18 22:25
OK, better but not good enough... By the way I actually had to create target/ecrro to get the following errors, otherwise I got the same error as above:

/tools/odk.py:439: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  obj = yaml.load(config_file)
INFO:root:Created files:
INFO:root:  File: target/ecrro/project.yaml
INFO:root:RUNNING: cd target/ecrro && git init && git add ./project.yaml
INFO:root:OUT: {}
ERROR:root:b"warning: unable to access '/root/.gitconfig': Is a directory\nfatal: unknown error occurred while reading the configuration files\n"
Traceback (most recent call last):
  File "/tools/odk.py", line 673, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tools/odk.py", line 638, in seed
    files=" ".join([t.replace(outdir, ".", 1) for t in tgts])))
  File "/tools/odk.py", line 667, in runcmd
    raise Exception('Failed: {}'.format(cmd))
Exception: Failed: cd target/ecrro && git init && git add ./project.yaml
Ruths-iMac:ResourceRegistry ruthduerr$

**Comment by matentzn** [comment] 2019-03-18 22:28
I am not at work today, I will check tomorrow. In the meantime: you can git clone the odk github project, place your project.yaml file in the root directory and run the same code from in there.. let me know if that fails too, because then we have a more serious problem..

**Comment by rduerr** [comment] 2019-03-18 22:38
will do

**Comment by rduerr** [comment] 2019-03-18 23:06
And this is the result... though it looks like a pretty complete directory tree was created under eccro...

$ ./seed-via-docker.sh -C project.yaml
/tools/odk.py:439: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  obj = yaml.load(config_file)
INFO:root:  Copying: ./template/issue_template.md.jinja2 -> target/ecrro/issue_template.md.jinja2
INFO:root:  Copying: ./template/CONTRIBUTING.md.jinja2 -> target/ecrro/CONTRIBUTING.md.jinja2
INFO:root:  Copying: ./template/_dynamic_files.jinja2 -> target/ecrro/_dynamic_files.jinja2
INFO:root:  Copying: ./template/.travis.yml.jinja2 -> target/ecrro/.travis.yml.jinja2
INFO:root:  Copying: ./template/README.md.jinja2 -> target/ecrro/README.md.jinja2
INFO:root:  Copying: ./template/.gitignore.jinja2 -> target/ecrro/.gitignore.jinja2
INFO:root:Applying templates
INFO:root:  Compiling: ./template/issue_template.md.jinja2 -> target/ecrro/issue_template.md
INFO:root:  Compiling: ./template/CONTRIBUTING.md.jinja2 -> target/ecrro/CONTRIBUTING.md
INFO:root:  Unpacking: target/ecrro/_dynamic_files
INFO:root:  Unpacking into: target/ecrro/src/ontology/ecrro-edit.owl
INFO:root:  Unpacking into: target/ecrro/src/ontology/ecrro-idranges.owl
INFO:root:  Unpacking into: target/ecrro/src/ontology/ecrro.Makefile
INFO:root:  Unpacking into: target/ecrro/src/ontology/imports/ro_import.owl
INFO:root:  Unpacking into: target/ecrro/src/ontology/imports/ro_terms.txt
INFO:root:  Unpacking into: target/ecrro/src/ontology/imports/bfo_import.owl
INFO:root:  Unpacking into: target/ecrro/src/ontology/imports/bfo_terms.txt
INFO:root:  Unpacking into: target/ecrro/src/ontology/imports/pato_import.owl
INFO:root:  Unpacking into: target/ecrro/src/ontology/imports/pato_terms.txt
INFO:root:  Unpacking into: target/ecrro/src/metadata/ecrro.md
INFO:root:  Unpacking into: target/ecrro/src/metadata/ecrro.yml
INFO:root:  Unpacking into: target/ecrro/src/sparql/ecrro_terms.sparql
INFO:root:  Compiling: ./template/.travis.yml.jinja2 -> target/ecrro/.travis.yml
INFO:root:  Compiling: ./template/README.md.jinja2 -> target/ecrro/README.md
INFO:root:  Compiling: ./template/.gitignore.jinja2 -> target/ecrro/.gitignore
INFO:root:Applying templates
INFO:root:  Copying: ./template/src/sparql/obsoletes.sparql -> target/ecrro/src/sparql/obsoletes.sparql
INFO:root:  Copying: ./template/src/sparql/basic-report.sparql -> target/ecrro/src/sparql/basic-report.sparql
INFO:root:  Copying: ./template/src/sparql/synonyms.sparql -> target/ecrro/src/sparql/synonyms.sparql
INFO:root:  Copying: ./template/src/sparql/obsolete-violation.sparql -> target/ecrro/src/sparql/obsolete-violation.sparql
INFO:root:  Copying: ./template/src/sparql/nolabels-violation.sparql -> target/ecrro/src/sparql/nolabels-violation.sparql
INFO:root:  Copying: ./template/src/sparql/subsets-labeled.sparql -> target/ecrro/src/sparql/subsets-labeled.sparql
INFO:root:  Copying: ./template/src/sparql/def-lacks-xref-violation.sparql -> target/ecrro/src/sparql/def-lacks-xref-violation.sparql
INFO:root:  Copying: ./template/src/sparql/redundant-subClassOf-violation.sparql -> target/ecrro/src/sparql/redundant-subClassOf-violation.sparql
INFO:root:  Copying: ./template/src/sparql/owldef-self-reference-violation.sparql -> target/ecrro/src/sparql/owldef-self-reference-violation.sparql
INFO:root:  Copying: ./template/src/sparql/labels.sparql -> target/ecrro/src/sparql/labels.sparql
INFO:root:  Copying: ./template/src/sparql/xref-syntax-violation.sparql -> target/ecrro/src/sparql/xref-syntax-violation.sparql
INFO:root:  Copying: ./template/src/sparql/xrefs.sparql -> target/ecrro/src/sparql/xrefs.sparql
INFO:root:  Copying: ./template/src/sparql/owldef-violation.sparql -> target/ecrro/src/sparql/owldef-violation.sparql
INFO:root:  Copying: ./template/src/sparql/trailing-whitespace-violation.sparql -> target/ecrro/src/sparql/trailing-whitespace-violation.sparql
INFO:root:  Copying: ./template/src/sparql/edges.sparql -> target/ecrro/src/sparql/edges.sparql
INFO:root:  Copying: ./template/src/sparql/class-count-by-prefix.sparql -> target/ecrro/src/sparql/class-count-by-prefix.sparql
INFO:root:  Copying: ./template/src/sparql/terms.sparql -> target/ecrro/src/sparql/terms.sparql
INFO:root:  Copying: ./template/src/sparql/README.md.jinja2 -> target/ecrro/src/sparql/README.md.jinja2
INFO:root:  Copying: ./template/src/sparql/equivalent-classes-violation.sparql -> target/ecrro/src/sparql/equivalent-classes-violation.sparql
INFO:root:Applying templates
INFO:root:  Compiling: ./template/src/sparql/README.md.jinja2 -> target/ecrro/src/sparql/README.md
INFO:root:  Copying: ./template/src/patterns/definitions.owl.jinja2 -> target/ecrro/src/patterns/definitions.owl.jinja2
INFO:root:  Copying: ./template/src/patterns/pattern.owl.jinja2 -> target/ecrro/src/patterns/pattern.owl.jinja2
INFO:root:  Copying: ./template/src/patterns/README.md -> target/ecrro/src/patterns/README.md
INFO:root:Applying templates
INFO:root:  Compiling: ./template/src/patterns/definitions.owl.jinja2 -> target/ecrro/src/patterns/definitions.owl
INFO:root:  Compiling: ./template/src/patterns/pattern.owl.jinja2 -> target/ecrro/src/patterns/pattern.owl
INFO:root:  Copying: ./template/src/patterns/dosdp-patterns/external.txt -> target/ecrro/src/patterns/dosdp-patterns/external.txt
INFO:root:Applying templates
INFO:root:  Copying: ./template/src/ontology/prepare_release.sh -> target/ecrro/src/ontology/prepare_release.sh
INFO:root:  Copying: ./template/src/ontology/ontologyterms.txt -> target/ecrro/src/ontology/ontologyterms.txt
INFO:root:  Copying: ./template/src/ontology/README-editors.md.jinja2 -> target/ecrro/src/ontology/README-editors.md.jinja2
INFO:root:  Copying: ./template/src/ontology/catalog-v001.xml.jinja2 -> target/ecrro/src/ontology/catalog-v001.xml.jinja2
INFO:root:  Copying: ./template/src/ontology/run.bat -> target/ecrro/src/ontology/run.bat
INFO:root:  Copying: ./template/src/ontology/Dockerfile -> target/ecrro/src/ontology/Dockerfile
INFO:root:  Copying: ./template/src/ontology/run.sh.jinja2 -> target/ecrro/src/ontology/run.sh.jinja2
INFO:root:  Copying: ./template/src/ontology/build.sh -> target/ecrro/src/ontology/build.sh
INFO:root:  Copying: ./template/src/ontology/Makefile.jinja2 -> target/ecrro/src/ontology/Makefile.jinja2
INFO:root:  Copying: ./template/src/ontology/patterns.sh -> target/ecrro/src/ontology/patterns.sh
INFO:root:  Copying: ./template/src/ontology/keeprelations.txt -> target/ecrro/src/ontology/keeprelations.txt
INFO:root:  Copying: ./template/src/ontology/test.sh -> target/ecrro/src/ontology/test.sh
INFO:root:Applying templates
INFO:root:  Compiling: ./template/src/ontology/README-editors.md.jinja2 -> target/ecrro/src/ontology/README-editors.md
INFO:root:  Compiling: ./template/src/ontology/catalog-v001.xml.jinja2 -> target/ecrro/src/ontology/catalog-v001.xml
INFO:root:  Compiling: ./template/src/ontology/run.sh.jinja2 -> target/ecrro/src/ontology/run.sh
INFO:root:  Compiling: ./template/src/ontology/Makefile.jinja2 -> target/ecrro/src/ontology/Makefile
INFO:root:  Copying: ./template/src/ontology/reports/README.md -> target/ecrro/src/ontology/reports/README.md
INFO:root:Applying templates
INFO:root:  Copying: ./template/src/metadata/README.md.jinja2 -> target/ecrro/src/metadata/README.md.jinja2
INFO:root:Applying templates
INFO:root:  Compiling: ./template/src/metadata/README.md.jinja2 -> target/ecrro/src/metadata/README.md
INFO:root:Created files:
INFO:root:  File: target/ecrro/issue_template.md
INFO:root:  File: target/ecrro/CONTRIBUTING.md
INFO:root:  File: target/ecrro/src/ontology/ecrro-edit.owl
INFO:root:  File: target/ecrro/src/ontology/ecrro-idranges.owl
INFO:root:  File: target/ecrro/src/ontology/ecrro.Makefile
INFO:root:  File: target/ecrro/src/ontology/imports/ro_import.owl
INFO:root:  File: target/ecrro/src/ontology/imports/ro_terms.txt
INFO:root:  File: target/ecrro/src/ontology/imports/bfo_import.owl
INFO:root:  File: target/ecrro/src/ontology/imports/bfo_terms.txt
INFO:root:  File: target/ecrro/src/ontology/imports/pato_import.owl
INFO:root:  File: target/ecrro/src/ontology/imports/pato_terms.txt
INFO:root:  File: target/ecrro/src/metadata/ecrro.md
INFO:root:  File: target/ecrro/src/metadata/ecrro.yml
INFO:root:  File: target/ecrro/src/sparql/ecrro_terms.sparql
INFO:root:  File: target/ecrro/.travis.yml
INFO:root:  File: target/ecrro/README.md
INFO:root:  File: target/ecrro/.gitignore
INFO:root:  File: target/ecrro/src/sparql/obsoletes.sparql
INFO:root:  File: target/ecrro/src/sparql/basic-report.sparql
INFO:root:  File: target/ecrro/src/sparql/synonyms.sparql
INFO:root:  File: target/ecrro/src/sparql/obsolete-violation.sparql
INFO:root:  File: target/ecrro/src/sparql/nolabels-violation.sparql
INFO:root:  File: target/ecrro/src/sparql/subsets-labeled.sparql
INFO:root:  File: target/ecrro/src/sparql/def-lacks-xref-violation.sparql
INFO:root:  File: target/ecrro/src/sparql/redundant-subClassOf-violation.sparql
INFO:root:  File: target/ecrro/src/sparql/owldef-self-reference-violation.sparql
INFO:root:  File: target/ecrro/src/sparql/labels.sparql
INFO:root:  File: target/ecrro/src/sparql/xref-syntax-violation.sparql
INFO:root:  File: target/ecrro/src/sparql/xrefs.sparql
INFO:root:  File: target/ecrro/src/sparql/owldef-violation.sparql
INFO:root:  File: target/ecrro/src/sparql/trailing-whitespace-violation.sparql
INFO:root:  File: target/ecrro/src/sparql/edges.sparql
INFO:root:  File: target/ecrro/src/sparql/class-count-by-prefix.sparql
INFO:root:  File: target/ecrro/src/sparql/terms.sparql
INFO:root:  File: target/ecrro/src/sparql/equivalent-classes-violation.sparql
INFO:root:  File: target/ecrro/src/sparql/README.md
INFO:root:  File: target/ecrro/src/patterns/README.md
INFO:root:  File: target/ecrro/src/patterns/definitions.owl
INFO:root:  File: target/ecrro/src/patterns/pattern.owl
INFO:root:  File: target/ecrro/src/patterns/dosdp-patterns/external.txt
INFO:root:  File: target/ecrro/src/ontology/prepare_release.sh
INFO:root:  File: target/ecrro/src/ontology/ontologyterms.txt
INFO:root:  File: target/ecrro/src/ontology/run.bat
INFO:root:  File: target/ecrro/src/ontology/Dockerfile
INFO:root:  File: target/ecrro/src/ontology/build.sh
INFO:root:  File: target/ecrro/src/ontology/patterns.sh
INFO:root:  File: target/ecrro/src/ontology/keeprelations.txt
INFO:root:  File: target/ecrro/src/ontology/test.sh
INFO:root:  File: target/ecrro/src/ontology/README-editors.md
INFO:root:  File: target/ecrro/src/ontology/catalog-v001.xml
INFO:root:  File: target/ecrro/src/ontology/run.sh
INFO:root:  File: target/ecrro/src/ontology/Makefile
INFO:root:  File: target/ecrro/src/ontology/reports/README.md
INFO:root:  File: target/ecrro/src/metadata/README.md
INFO:root:  File: target/ecrro/project.yaml
INFO:root:RUNNING: cd target/ecrro && git init && git add ./issue_template.md ./CONTRIBUTING.md ./src/ontology/ecrro-edit.owl ./src/ontology/ecrro-idranges.owl ./src/ontology/ecrro.Makefile ./src/ontology/imports/ro_import.owl ./src/ontology/imports/ro_terms.txt ./src/ontology/imports/bfo_import.owl ./src/ontology/imports/bfo_terms.txt ./src/ontology/imports/pato_import.owl ./src/ontology/imports/pato_terms.txt ./src/metadata/ecrro.md ./src/metadata/ecrro.yml ./src/sparql/ecrro_terms.sparql ./.travis.yml ./README.md ./.gitignore ./src/sparql/obsoletes.sparql ./src/sparql/basic-report.sparql ./src/sparql/synonyms.sparql ./src/sparql/obsolete-violation.sparql ./src/sparql/nolabels-violation.sparql ./src/sparql/subsets-labeled.sparql ./src/sparql/def-lacks-xref-violation.sparql ./src/sparql/redundant-subClassOf-violation.sparql ./src/sparql/owldef-self-reference-violation.sparql ./src/sparql/labels.sparql ./src/sparql/xref-syntax-violation.sparql ./src/sparql/xrefs.sparql ./src/sparql/owldef-violation.sparql ./src/sparql/trailing-whitespace-violation.sparql ./src/sparql/edges.sparql ./src/sparql/class-count-by-prefix.sparql ./src/sparql/terms.sparql ./src/sparql/equivalent-classes-violation.sparql ./src/sparql/README.md ./src/patterns/README.md ./src/patterns/definitions.owl ./src/patterns/pattern.owl ./src/patterns/dosdp-patterns/external.txt ./src/ontology/prepare_release.sh ./src/ontology/ontologyterms.txt ./src/ontology/run.bat ./src/ontology/Dockerfile ./src/ontology/build.sh ./src/ontology/patterns.sh ./src/ontology/keeprelations.txt ./src/ontology/test.sh ./src/ontology/README-editors.md ./src/ontology/catalog-v001.xml ./src/ontology/run.sh ./src/ontology/Makefile ./src/ontology/reports/README.md ./src/metadata/README.md ./project.yaml
INFO:root:OUT: {}
ERROR:root:b"warning: unable to access '/root/.gitconfig': Is a directory\nfatal: unknown error occurred while reading the configuration files\n"
Traceback (most recent call last):
  File "/tools/odk.py", line 673, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tools/odk.py", line 638, in seed
    files=" ".join([t.replace(outdir, ".", 1) for t in tgts])))
  File "/tools/odk.py", line 667, in runcmd
    raise Exception('Failed: {}'.format(cmd))
Exception: Failed: cd target/ecrro && git init && git add ./issue_template.md ./CONTRIBUTING.md ./src/ontology/ecrro-edit.owl ./src/ontology/ecrro-idranges.owl ./src/ontology/ecrro.Makefile ./src/ontology/imports/ro_import.owl ./src/ontology/imports/ro_terms.txt ./src/ontology/imports/bfo_import.owl ./src/ontology/imports/bfo_terms.txt ./src/ontology/imports/pato_import.owl ./src/ontology/imports/pato_terms.txt ./src/metadata/ecrro.md ./src/metadata/ecrro.yml ./src/sparql/ecrro_terms.sparql ./.travis.yml ./README.md ./.gitignore ./src/sparql/obsoletes.sparql ./src/sparql/basic-report.sparql ./src/sparql/synonyms.sparql ./src/sparql/obsolete-violation.sparql ./src/sparql/nolabels-violation.sparql ./src/sparql/subsets-labeled.sparql ./src/sparql/def-lacks-xref-violation.sparql ./src/sparql/redundant-subClassOf-violation.sparql ./src/sparql/owldef-self-reference-violation.sparql ./src/sparql/labels.sparql ./src/sparql/xref-syntax-violation.sparql ./src/sparql/xrefs.sparql ./src/sparql/owldef-violation.sparql ./src/sparql/trailing-whitespace-violation.sparql ./src/sparql/edges.sparql ./src/sparql/class-count-by-prefix.sparql ./src/sparql/terms.sparql ./src/sparql/equivalent-classes-violation.sparql ./src/sparql/README.md ./src/patterns/README.md ./src/patterns/definitions.owl ./src/patterns/pattern.owl ./src/patterns/dosdp-patterns/external.txt ./src/ontology/prepare_release.sh ./src/ontology/ontologyterms.txt ./src/ontology/run.bat ./src/ontology/Dockerfile ./src/ontology/build.sh ./src/ontology/patterns.sh ./src/ontology/keeprelations.txt ./src/ontology/test.sh ./src/ontology/README-editors.md ./src/ontology/catalog-v001.xml ./src/ontology/run.sh ./src/ontology/Makefile ./src/ontology/reports/README.md ./src/metadata/README.md ./project.yaml
Ruths-iMac:ontology-development-kit-master ruthduerr$

**Comment by matentzn** [comment] 2019-03-18 23:08
Ah, I think you can use this now. Do you have git installed on your machine? Linux or Mac?

**Comment by matentzn** [comment] 2019-03-18 23:09
The error means that the install script cant find your git config which is usually stored in your home directory... We need to sort this somehow.

**Comment by rduerr** [comment] 2019-03-18 23:10
Mac and yes… though maybe it needs an update…. - Ruth

**Comment by matentzn** [comment] 2019-03-18 23:17
can you check whether there is a .gitconfig file in your user directory (e.g. you can run: `cat ~/.gitconfig`)? If not find out where it is located?

**Comment by cmungall** [comment] 2019-03-18 23:38
> Do you have git installed on your machine?

This shouldn't be relevant, as git is being run from inside the docker container

> can you check whether there is a .gitconfig file in your user directory

This is on the right path. The wrapper script assumes that you have this already (it maps `-v $HOME/.gitconfig:/root/.gitconfig`).

I'm not sure there is an easy way around this and for ODK to Do The Right Thing in all circumstances, but we can at least document this better...

**Comment by matentzn** [comment] 2019-03-18 23:41
Yeah I thought probably wrongly that the existence of the .gitconfig file is related to having git installed :P Thats why I asked. Maybe we can serve a default .gitconfig file that people can copy to their user dir if this error happens?

**Comment by cmungall** [comment] 2019-03-18 23:48
Seems reasonable

**Comment by matentzn** [comment] 2019-03-19 11:26
@rduerr , did you check whether you have a .gitconfig file anywhere on your system? If so, where it is located?

**Comment by rduerr** [comment] 2019-03-19 16:35
Well, I don’t have one in my top level directory.  Still hunting around in other places….

Ruth

**Comment by matentzn** [comment] 2019-03-19 17:06
it is possible you dont have one. Rare, if you have git installed, but possible! 

if you run git config --global --edit, maybe you can see the location of the file somehow?

**Comment by rduerr** [comment] 2019-03-19 17:09
Nope - I get the same error…

warning: unable to access '/Users/ruthduerr/.gitconfig': Is a directory
fatal: unknown error occurred while reading the configuration files

**Comment by cmungall** [comment] 2019-03-19 17:14
Ah, that is odd. It looks like your gitconfig is a directory!

what is the output of
find /Users/ruthduerr/.gitconfig

**Comment by rduerr** [comment] 2019-03-19 17:28
Done…. Which is weird because, well just look at the following:

Ruths-iMac:bin ruthduerr$ git config --global --edit
warning: unable to access '/Users/ruthduerr/.gitconfig': Is a directory
fatal: unknown error occurred while reading the configuration files
Ruths-iMac:bin ruthduerr$ ls -ltr .gitconfig
ls: .gitconfig: No such file or directory
Ruths-iMac:bin ruthduerr$ find /Users/ruthduerr/.gitconfig
/Users/ruthduerr/.gitconfig
Ruths-iMac:bin ruthduerr$ mv /Users/ruthduerr/.gitconfig /Users/ruthduerr/.gitconfig-dir
Ruths-iMac:bin ruthduerr$ find /Users/ruthduerr/.gitconfig
find: /Users/ruthduerr/.gitconfig: No such file or directory
Ruths-iMac:bin ruthduerr$ git config --global --edit
Ruths-iMac:bin ruthduerr$ find /Users/ruthduerr/.gitconfig
/Users/ruthduerr/.gitconfig
Ruths-iMac:bin ruthduerr$ 

So now what?

Ruth

**Comment by matentzn** [comment] 2019-03-19 17:31
After you do a `cat ~/.gitconfig` and verified that the file there now contains a username, you can run the odk! (./seed-via-docker.sh -C project.yaml). As a tip: add -c to overwrite the old attempts, like so:
```
./seed-via-docker.sh -c -C project.yaml
```

**Comment by matentzn** [comment] 2019-03-19 17:32
my .gitconfig file looks like this:
```
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
[user]
	name = matentzn
	email = nicolas.matentzoglu@gmail.com
```

**Comment by rduerr** [comment] 2019-03-20 18:30
Interestingly enough, I was back to the original error, so had to run "./seed-via-docker.sh -c -C project.yaml” from my own installation of ODK built yesterday; but at least it completed successfully!

However, you might want to note the following error, which occurred no matter where I put the project.yaml file…. That implies to me that there is still a problem with the installation code...

Ruths-iMac:ResourceRegistry ruthduerr$ ./seed-via-docker.sh -c -C project.yaml
/tools/odk.py:439: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  obj = yaml.load(config_file)
Traceback (most recent call last):
  File "/tools/odk.py", line 673, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tools/odk.py", line 629, in seed
    save_project_yaml(project, tgt_project_file)
  File "/tools/odk.py", line 464, in save_project_yaml
    with open(path, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'target/ecrro/project.yaml'


Lastly, my new .gitconfig file just has the user lines in it (with my name and email)

Ruth

**Comment by matentzn** [comment] 2019-03-20 18:47
Yeah, if you currently run the code without the ODK directory structure, it will fail in this way. Someone needs to urgently look at this, and it should be very easy to fix. Thanks for all the info. So is everything working for you now?

**Comment by rduerr** [comment] 2019-03-20 19:06
So far so good.  Am working on understanding the OBO way of editing, testing and such.  Hope to have a 2nd commit and push later today.

Ruth

**Comment by cmungall** [comment] 2019-03-20 19:09
@matentzn this is puzzling, as it seems that the code defensively makes the target directory if not present:

https://github.com/INCATools/ontology-development-kit/blob/463231c2b113649e397e3a3c8c8ec4d35cc9f804/odk/odk.py#L481

**Comment by matentzn** [comment] 2019-03-20 19:59
I remember trying the no-odk-repo solution (downloading the seed script) and having the same problem a while ago. but let’s keep this open and seek to fix this.

**Comment by matentzn** [comment] 2020-03-06 17:24
Both issues are fixed now (error messages by yaml Loader and direct run of seed-my-repo of ODK according to instructions! Please reopen if further issues!

**Closed by matentzn** 2020-03-06 17:24 UTC
