### ISSUE TITLE
Migrate docker base image to avoid DNS issues

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#302] opened 2019-12-20 17:28 UTC
From @kltm:

```
The terminal generated command seems to be:

curl -L -o mirror/uberon.owl.tmp.owl
http://purl.obolibrary.org/obo/uberon.owl

Failing with:

curl: (6) Could not resolve host: ontologies.berkeleybop.org

Playing more, it is actually semi-random: can get the same problem with
ping:

/tmp/mammalian-phenotype-ontology/src/ontology # ping
ontologies.berkeleybop.org
ping: bad address 'ontologies.berkeleybop.org'
/tmp/mammalian-phenotype-ontology/src/ontology # ping
ontologies.berkeleybop.org
PING ontologies.berkeleybop.org (13.35.127.20): 56 data bytes
64 bytes from 13.35.127.20: seq=0 ttl=245 time=2.393 ms

I'd note here that the alpine image that the odk is based on makes some
kinds of debugging quite hard. I'd recommend basing on something
minimal, but with a few more features. Playing around some:

This does not happen on my local machine.
This does not happen in the ODK image on my local machine.
This does not happen on the Jenkins machine.
This does not happen on the Jenkins machine with an Ubuntu docker image.
This does not (so far seem to) happen on the Jenkins machine with
obolibrary/odkfull:v1.1.7.
This only seems to happen on the Jenkins machine with the current
obolibrary/odkfull:latest.
```

It seems there may be a known issue with DNS on alpine:

 - https://github.com/gliderlabs/docker-alpine/issues/476
 - https://unix.stackexchange.com/questions/441664/alpine-linux-sometimes-dns-is-not-resolved
 - https://forums.docker.com/t/resolved-service-name-resolution-broken-on-alpine-and-docker-1-11-1-cs1/19307/22

**Comment by kltm** [comment] 2019-12-20 21:03
While there are known issues (I looked at a few of them yesterday and walked through the Dockerfile history), the fact that I can consistently cause the problem to occur on one machine but I cannot on the other means that at least part of the problem is the interaction between the current image (likely at the base), docker, and the host system. As I've never run into something quite like that before, and it's likely something pretty deep, I think the fastest way forward would be to switch base images, at least away from what is currently there and ideally to something more "robust".

**Comment by cmungall** [comment] 2019-12-20 21:31
Could it be the version of Docker that is used on the problematic machine?

**Comment by kltm** [comment] 2019-12-20 21:43
It sure could, or at least partially, as the earlier alpine image "worked". However, in this case it's 19.03.5 in both places (although different on one other test where I couldn't get the error). But maybe it's the kernel then against a particular docker runtime...

I think in this case, the most easily controllable option is the Dockerfile base image, as that one is consistent as a necessity in the issue we're having. It could, in the end, be an issue somewhere else along the line, but we probably don't want to spend too long learning system internals. (Although somebody may crack it; who knows right now.)

**Comment by kltm** [comment] 2019-12-20 21:45
I did actually spend a little time trying to reboot and restart systems and services, doing various updates, hoping that it would be just "one of those things". No luck however.

**Comment by matentzn** [comment] 2020-01-02 15:40
Oh thanks all for spending so much effort to look into this! I will first patch the immediate issue for the MP folks and then proceed to look into the more general issue. I kinda would like switching the base image as a sort of last resort - I know that some (maybe not too many) commands are slightly different on alpine then say normal ubuntu (wget to start with). Anyways, thanks a lot for all the effort troubleshooting, I will take it from here!

**Comment by matentzn** [comment] 2020-01-02 18:52
As described in the email, redirecting all urls pointing to berkeleybop servers to EBI patched the problem; I will continue from there.

**Comment by kltm** [comment] 2020-01-05 18:46
@matentzn @cmungall (re: https://github.com/INCATools/ontology-development-kit/issues/302#issuecomment-570245014 ), I think that overall it would be good to start reducing the number of base images in use for various projects: this allows expertise to build up more uniformly and, in this case, remove a problematic image. As Ubuntu is standard as a base for servers and pipelines in Monarch and GO, I'd suggest heading in that direction.

**Comment by matentzn** [comment] 2020-01-06 13:39
This is the kind of argument I can get behind! :) Cool. 

In any case: the ploy with simply rebuilding the ODK failed. Still the same error (ODK 1.2.20). I want to mention that despite the DNS error that you shared from stackoverflow, which is our current best hypothesis, there is also something potentially wrong with the way the way the jenkins-docker module interacts with the berkleybop domain. Also, from reading through related docker-dns threads, it appears to me that the error originates sometimes from the container orchestration system (i.e. kybernetes) and not the docker environment per se. Maybe it has to do with firewall configurations of bbop. Did anything of important change on the bbop servers around mid December 2019?

If there is no better idea, I guess we can move to a better base image (we should do that anyways I guess given your argument above). Can you share a docker file that inherits from the best base? I will then simply move on to migrate to that and see whether that fixes the problem.

**Comment by kltm** [comment] 2020-01-06 20:34
@matentzn I do not believe there is any issue with the jenkins-docker module for us in this case--we have two other jenkins instances that work fine with the domain, including one that makes heavy use of ODK. We do not make any use of kubernetes.

**Comment by matentzn** [comment] 2020-01-07 15:51
yeah, probably not.. :P Just poking in the dark. Ok lets try the base image switch route. So from browsing real quick:

- [OWLSIM](https://github.com/monarch-initiative/owlsim-v3/blob/ff78d1d1e7a48b3318e2c79f54507580670690dc/Dockerfile)
- [Scigraph NCATS](https://github.com/monarch-initiative/SciGraph-docker-ncats/blob/aecacd9aaaf70d4ac00fadcd84828121cf15f4dc/src/main/resources/Dockerfile-load)

you propose to use 

```
FROM ubuntu:16.04
```

as the base image? If this does not blow up the ODK image size too much, maybe this could be the way to go.

**Comment by kltm** [comment] 2020-01-07 23:24
Looking at what we use and https://hub.docker.com/_/ubuntu/, I would propose the latest LTS `18.04` (although that's switching in April). That said, I would consider `16.04` good enough for the moment, but would note that support for it runs out 2021-04.

**Comment by matentzn** [comment] 2020-01-23 12:20
For the record, I tried to upgrade to the latest alpine image, and the problem persists. I now started migrating to `ubuntu:18.04`.

**Comment by matentzn** [comment] 2020-01-23 12:21
Also we need to be a bit careful with java versions: I notices that dosdp tools has problem when java 14 is installed..

**Comment by balhoff** [comment] 2020-01-23 12:52
I think most GO software is still being deployed on java 8. Scala-based stuff should be fine on java 11, but not higher. Java 11 is the newest LTS version anyway.

**Comment by matentzn** [comment] 2020-01-23 12:52
Ok no problem in any case; thanks for the clarification.

**Comment by matentzn** [comment] 2020-01-23 12:58
The first good news is that the image is actually not much larger (actually seems more or less the same, since ammonite is now in the mix).

https://hub.docker.com/r/obolibrary/odkdev/tags

I will need some help eventually to shrink the image. Please do not use it until I give green light. It only just passed the first very crude test. You will be pleased to know @kltm that your hunch was right - the issue is now fixed. However, as this is a major change, I will not update the main odk (obolibrary/odkfull) until all tests have passed.

**Comment by matentzn** [comment] 2020-01-23 13:04
If the following run:

- [X] python3
- [ ] pandas
- [ ] dosdp
- [ ] konclude
- [ ] owltools
- [X] ROBOT
- [X] ODK seeding

@balhoff do you think that covers it? Probably :D

**Comment by matentzn** [comment] 2020-01-23 17:16
Fixed in https://github.com/INCATools/ontology-development-kit/pull/307

**Closed by matentzn** 2020-01-23 17:16 UTC
