### ISSUE TITLE
trying to run odk in windows 11

### ISSUE THREAD

**Issue by luisenriqueramos1977** [INCATools/ontology-development-kit#728] opened 2022-11-02 09:25 UTC
Dear all,

I am using Docker Desktop to manage obolibrary/odkfull image, I downloaded it using the following command:
1. docker pull obolibrary/odkfull
Then, when I try to run a container from Docker Desktop, it starts but also stops right away.

It also called my attention that starting the container of odk seems to produce the stopping and starting of the other running containers.

What should I be doing wrong?, I have not experimented such issue in ubuntu.

Best regards

Luis Ramos

**Comment by gouttegd** [comment] 2022-11-02 10:17
Unfortunately most if not all of us ODK developers are working on either Mac OS or GNU/Linux, so the support we can provide for Windows is somewhat limited…

Could you try starting the container from the command line instead of from Docker Desktop:

```cmd
docker run --rm -ti obolibrary/odkfull
```

?

This way you might get an error message that could help us figure out what the problem is.

For now, the only somewhat plausible explanation I can think of is that your Docker Desktop client might be configured by default to use Windows containers – if that’s the case, you would need to switch it to Linux containers.

**Comment by luisenriqueramos1977** [comment] 2022-11-02 12:38
Thanks for your quick answer @gouttegd!.

When I run the command this is the message I received:
**Usage: odk.py [OPTIONS] COMMAND [ARGS]...
Options:
  --help  Show this message and exit.
Commands:
  create-dynfile   For testing purposes
  create-makefile  For testing purposes
  dump-schema      Dumps the python schema as json schema.
  export-project   For testing purposes
  seed             Seeds an ontology project**

After that, I ran the command: **docker container ls**

So, I confirmed no container for obolibrary/odkfull was created.

Hope to get some clues on how to solve this issue.


Luis Ramos

**Comment by gouttegd** [comment] 2022-11-02 14:36
Well, this is the expected behaviour.

The ODK is not a long-running container. You do not start an ODK container that would then provide a long-running service. Instead, whenever you need one of the tools provided by the ODK (ROBOT, OAK, Konclude, etc.), you invoke the ODK with the command you want to run, a container is started just to run that command, and the container is automatically destroyed as soon as the command has finished its task.

If you do not specify a command to run, the default is to call the `odk.py` script (which is used to create and maintain ODK-managed repositories), which then displays its help message and then terminates.

Were you expecting something else?

**Comment by luisenriqueramos1977** [comment] 2022-11-03 07:40
Thanks for your quick answer @gouttegd, I am simply trying to create a repository or ODK project.
As I understand from here:
**https://oboacademy.github.io/obook/howto/odk-create-repo/**
After pulling the ODK, then, I have to run this command to create my test repository:
**seed-via-docker.bat -d po -d ro -d pato -u luisenriqueramos1977 -t "Test ontology" testonto**
However, I obtained this result:
**The "seed-via-docker.bat" command is either misspelled or could not be found.**
So, I wonder where do I find this .bat file, or how do I access to it?. or is the command wrong?


Luis

**Comment by luisenriqueramos1977** [comment] 2022-11-03 07:57
Solved!
I have not downloaded the script seed-via-docker.bat, nor stored it in the respective folder.

After doing it, and running the command:
 seed-via-docker.bat -d po -d ro -d pato -u luisenriqueramos1977 -t "Test ontology" testonto

The odk project is created.

Luis Ramos

**Comment by gouttegd** [comment] 2022-11-03 09:08
Perfect. Closing here, then. :)

**Closed by gouttegd** 2022-11-03 09:08 UTC
Labels: bug
