### ISSUE TITLE
Building ontology with equivalent classes breaks the taxonomy

### ISSUE THREAD

**Issue by nleguillarme** [INCATools/ontology-development-kit#345] opened 2020-06-09 14:47 UTC
Hi.

When building my ontology, which contains equivalence axioms, this breaks the taxonomy for these equivalent classes in onto-full.owl.
Are equivalent classes allowed in the ODK workflow ?

**Comment by matentzn** [comment] 2020-06-09 15:52
This is a matter of how you set the respective parameter, check for example here: https://github.com/INCATools/ontology-development-kit/blob/4c01ef1e7cba7010f1658ccd1d2844775eed45b9/configs/mp-odk.yaml#L40

The parameters you can use are defined by ROBOT, here:
http://robot.obolibrary.org/reason#equivalent-class-axioms

So: 

- `all`: always allow all equivalent classes
- `none`: do not allow any equivalent classes
- `asserted-only`: prevent inferred subscriptions, but allow asserted ones (this is the ODK default)

**Comment by nleguillarme** [comment] 2020-06-09 16:10
Actually, allow_equivalents is set to "all" in all the projects I generated with ODK.
Does it explain the "broken taxonomy' behavior ?
And if so, what should I do after changing the value of the allow_equivalents field ? Should I regenerate something ? (I tried changing the value and "make all" again, without success).

Sorry for all the questions, but I am still quite confused with the build workflow.

**Comment by matentzn** [comment] 2020-06-09 16:11
Can you share the error message/log?

**Comment by nleguillarme** [comment] 2020-06-09 16:47
Well there is no error message. But when I do 
`./run.sh make all` in src/ontology, the result in onto-full.owl is the same, whether I set allow_equivalents to all, to none or to asserted-only in project.yaml.

**Comment by matentzn** [comment] 2020-06-09 16:51
I think I misunderstand your problem then! Setting this parameter does absolutely nothing to the ontology - it simply tells ROBOT to fail hard if such an equivalence is detected.. It will not fix it.

So what do you mean by "broken taxonomy"?

**Comment by nleguillarme** [comment] 2020-06-09 17:03
Ok, suppose I have the following taxonomy in onto-edit.owl :

Thing
   Organism
       Decomposer
          Coprophage
          Detritivore (equivalentTo Saprophage)
          Saprophage (equivalentTo Detritivore)

After building with `make all`, here is the result in onto-full.owl :

Thing
   Detritivore (equivalentTo Saprophage, subclassOf Saprophage)
   Saprophage (equivalentTo Detritivore, subclassOf Detritivore)
   Organism
       Decomposer
          Coprophage
          
As you can see, Detritivore and Saprophage are not subclasses of Decomposer anymore.

By the way, I have no error message when building, whatever the value of allow_equivalents...

**Comment by balhoff** [comment] 2020-06-09 17:17
Are you running `robot reduce`? If so seems like it could be a bug there.

**Comment by nleguillarme** [comment] 2020-06-09 17:26
`robot reduce` appears twice in my Makefiles :

- Once in the $(ONT)-full.owl target in the default Makefile
- Once in the imports/ecocore_import.owl target in my custom Makefile

**Comment by matentzn** [comment] 2020-06-09 18:24
Is your ontology project on github or gitlab by any chance? In your example, I dont see how Decomposer was a superclass of Detritivore; maybe the indentation got lost! If you can point me to the file, Jim and I may be able to help you out.

**Comment by nleguillarme** [comment] 2020-06-09 18:51
Oh sorry, I didn't see that the hierarchy was lost in my message. Coprophage, saprophage and detritivore are all subclasses of decomposer in onto-edit.owl. Saprophage and detritivore are subclass of Thing in onto-full.owl.

I invited you both as collaborators of my project (private for the moment).

**Comment by matentzn** [comment] 2020-06-09 21:08
Hmmmm.... I cant exactly pinpoint the issue, but I think @balhoff was almost correct with his assumption; it seems the issue is caused by ROBOT relax though, rather than reduce. Add this to your trophgo.Makefile as a workaround for now:

```
$(ONT)-full.owl: $(SRC) $(OTHER_SRC)
	$(ROBOT) merge --input $< \
		reason --reasoner ELK --equivalent-classes-allowed asserted-only --exclude-tautologies structural \
		reduce -r ELK \
		annotate --ontology-iri $(ONTBASE)/$@ --version-iri $(ONTBASE)/releases/$(TODAY)/$@ --output $@.tmp.owl && mv $@.tmp.owl $@
```

I think it has to do with the fact that relax turns A=B into A sub B which creates a bunch of cycles - I cant debug this now, but we will leave this issue open to work on this for the future.. Can you check whether that works for you as a patch for now? I will inform you when a proper solution can be found.

**Comment by nleguillarme** [comment] 2020-06-11 13:07
Hi, me again, almost at the end of the road to the first release.

I just added a bunch of defining axioms of the type `Bacterivore 'equivalent to' heterotroph
 and ('capable of' some bactivory)` to my ontology.

Now, 'make all' returns unsatisfiable properties errors :
`2020-06-11 12:58:18,675 ERROR org.obolibrary.robot.ReasonerHelper - There are 28 unsatisfiable properties in the ontology.
2020-06-11 12:58:18,675 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable property: http://purl.obolibrary.org/obo/RO_0002213
2020-06-11 12:58:18,675 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable property: http://purl.obolibrary.org/obo/RO_0002418`
and so on...

I do not understand what the error is about... I just checked the onto-edit.owl file, the properties are not missing nor do related classes appear to be missing.

**Comment by balhoff** [comment] 2020-06-11 14:25
Hi @nleguillarme, here's how to look into this:
-  Open your edit file in Protégé.
- Select HermiT in the Reasoner menu, then Start reasoner.
- Go to the Entities tab, then the Object properties tab inside there.
- Click on 'capable of'; you will see it has been inferred equivalent to a huge number of other properties. It means all these properties have been inferred to be unsatisfiable (impossible to relate anything). This is due to some axiom that is conflicting with everything else.
- In the 'Description: capable of' panel, click the `?` button in the Equivalent To section.
- Feel frustrated that the explanation panel pops up with no explanation 😄 (it doesn't seem to work with properties)
- As a workaround, create a new class 'Capable'. Add an equivalence axiom to this class: `'capable of' some owl:Thing`.
- Run HermiT again.
- Now you will see that the new class is equivalent to owl:Nothing.
- Click on the `?` button next to this inference.
- You will see this: 

<img width="807" alt="capable" src="https://user-images.githubusercontent.com/210210/84398235-b44fde80-abcd-11ea-95da-885f8ba49e19.png">

I need to think through this explanation now.

**Comment by balhoff** [comment] 2020-06-11 14:29
The problematic axiom seems to be `'causally related to` SubPropertyOf `causal relation between material entity and a process`. This is in your ecocore import, but this is not in RO.

**Comment by balhoff** [comment] 2020-06-11 14:31
I don't see this relation in the ecocore release though.

**Comment by matentzn** [comment] 2020-06-11 15:33
Based on @balhoff strategy, I did a bid of digging; there are indeed a number of bad axioms in the current ecocore release..

Good solution:

1. Figure out why ecocore has old and bad RO axioms in there (did you recently refresh the import? do they have ancient RO axioms in there?)
2. On the [ecocore tracker](https://github.com/EcologicalSemantics/ecocore), tell people to get rid of the bad axioms
 
Bad solution:

you can add this to your `imports/ecocore_import.owl:` goal in throphgo.Makefile:

```
remove --term RO:0002410 --term RO:0002328 --axioms "subproperty" --preserve-structure false --trim true \
```

This will remove all the bad axioms from ecocore with causing you any further problems.

**Comment by matentzn** [comment] 2020-06-11 15:35
I also noticed you use both TROPHGO and TROPHRO as ID spaces.. Maybe better use just one.

**Comment by nleguillarme** [comment] 2020-06-12 09:21
I noticed a few things myself :
- In mirror/ecocore.owl : `causal relation between material entity and a process SubPropertyOf causally related to`, that's normal
- However, in imports/ecocore_import.owl, I have both : `causal relation between material entity and a process SubPropertyOf causally related to` and `causally related to SubPropertyOf causal relation between material entity and a process`
So, it seems that something weird happens when calling extract. Do robot performs any form of reasoning during extraction ?

**Comment by matentzn** [comment] 2020-06-12 09:35
No reasoning, extract produces true subsets.. the problem is with an outdated axiomatisation in ecocore.. I will contact them about it, but probably I will have to fix ecocore myself..

**Comment by matentzn** [comment] 2020-07-31 20:16
I will close this in favour of: https://github.com/INCATools/ontology-development-kit/issues/345

Feel free to reopen if necessary! Thank you for the input @nleguillarme @balhoff

**Closed by matentzn** 2020-07-31 20:16 UTC
